# Change these first
owner: antifake-ai # Your GitHub organization or username, where this repository lives
repo: masq-api-upptime # The name of this repository

sites:
  - name: Masq BE
    url: https://api.stealcut.org/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: ""
  baseUrl: /masq-api-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MASQ Status
  introTitle: "Service Status"
  introMessage: "Internal uptime checks for our backend API."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/antifake-ai/masq-api-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
notifications:
  slack:
    webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
